# Generated by Django 5.1.4 on 2024-12-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='About',
            new_name='content',
        ),
    ]
