# Generated by Django 5.0.4 on 2024-12-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
