# Generated by Django 5.0.4 on 2024-12-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0006_project_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='response',
        ),
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.TextField(blank=True),
        ),
    ]
